# Generated by Django 4.2.28 on 2026-02-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image'), ('CSV', 'CSV File')], max_length=10)),
                ('extracted_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
