# Generated by Django 4.2.28 on 2026-02-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('SYMPTOM', 'Symptom Analysis'), ('REPORT', 'Medical Report'), ('RECOMMENDATION', 'Recommendation'), ('EMERGENCY', 'Emergency Alert')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
