# Generated by Django 4.2.28 on 2026-02-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_engine', '0001_initial'),
        ('reports', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthhistory',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='reports.report'),
        ),
        migrations.AddField(
            model_name='healthhistory',
            name='symptom_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='ml_engine.symptomanalysis'),
        ),
    ]
