# Generated by Django 4.2.28 on 2026-02-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.JSONField(default=list)),
                ('exercise', models.JSONField(default=list)),
                ('lifestyle', models.JSONField(default=list)),
                ('medicines', models.JSONField(default=list)),
                ('specialist', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom_analysis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='ml_engine.symptomanalysis')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
