# Generated by Django 4.2.28 on 2026-02-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_text', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low - Monitor'), ('MEDIUM', 'Medium - See Doctor Soon'), ('HIGH', 'High - See Doctor Today'), ('CRITICAL', 'Critical - Call Emergency Services')], max_length=20)),
                ('triggered_keywords', models.JSONField(default=list)),
                ('recommended_action', models.TextField()),
                ('emergency_contact', models.CharField(default='911', max_length=50)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emergency_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
